name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Check pinned actions
        uses: suzuki-shunsuke/pinact-action@28aeb220eb3252ad0d4422dd5d9368e925acbd8d # v1.3.0
        with:
          fix: "false"
      - name: Install Rust components
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test --locked
      - name: Check compilation
        run: cargo check --locked
