name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check pinned actions
        uses: suzuki-shunsuke/pinact-action@28aeb220eb3252ad0d4422dd5d9368e925acbd8d # v1.3.0
        with:
          fix: "false"
      - name: Install Rust components
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test --locked
      - name: Check compilation
        run: cargo check --locked
